version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: kipaskipas_postgres
    environment:
      POSTGRES_DB: kipaskipas_database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
